In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Load dataset
file_path ="/8. Student Performance Prediction.csv"  # Absolute path
df = pd.read_csv(file_path)

# Drop non-useful columns
if 'StudentID' in df.columns:
    df = df.drop(['StudentID'], axis=1)

# Features and target
X = df.drop("GradeClass", axis=1)
y = df["GradeClass"]

# Scale numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Example prediction
example_student = np.array([[17, 1, 0, 2, 15, 5, 1, 2, 0, 0, 1, 0, 3.0]])
example_scaled = scaler.transform(example_student)
predicted_class = model.predict(example_scaled)
print(f"\nPredicted GradeClass for example student: {predicted_class[0]}")


Confusion Matrix:
[[ 11   4   3   2   2]
 [  1  42   1   1   4]
 [  1   2  74   4   4]
 [  0   2   2  77   5]
 [  0   1   0   3 233]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.85      0.50      0.63        22
         1.0       0.82      0.86      0.84        49
         2.0       0.93      0.87      0.90        85
         3.0       0.89      0.90      0.89        86
         4.0       0.94      0.98      0.96       237

    accuracy                           0.91       479
   macro avg       0.88      0.82      0.84       479
weighted avg       0.91      0.91      0.91       479


Predicted GradeClass for example student: 2.0


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
